### ISSUE TITLE
Script call on post-hook is wrong

### ISSUE THREAD

**Issue by WarMasterNL** [gitpel/letsencrypt-routeros#2]
Excellent script, but in the readme there are a few certbot commands to use depending on which situation you have. At the end of those commands there's a post-hook reference to the script posted here. However, this is the wrong filename in regard to the actual script provided.

The commands say: --post-hook /opt/letsencrypt-routeros/letsencrypt-routeros.sh
The file provided is actually: /opt/letsencrypt-routeros/letsencrypt-microtik.sh (Which is actually misspelled as it is mikrotik)

**Comment by gitpel** [comment]
Thank you! File was renamed 
٩(◕‿◕)۶
