### ISSUE TITLE
question about TXT Record

### ISSUE THREAD

**Issue by zstergios** [gitpel/letsencrypt-routeros#3]
Hi,
I 'm new to this.
The hostname of mikrotik is somthing that does not really exists, like my.router-hot.com

> In the first time, you will need to create Certificates manually and put domain TXT record

I read that Mikrotik has not DNS managment, so where I have to place the TXT record?

Sorry for my stupid question

**Comment by gitpel** [comment]
Hi, @zstergios 
You will need to add TXT record once, for the first time to your DNS management provider like GoDaddy, Cloudflare, On-Prem Server or etc.

You need to install "certbot" and execute it with params:
`certbot certonly --preferred-challenges=dns --manual -d my.router-hot.com`
And follow the steps from Certbot

Also take look how to add to TXT record to GoDaddy
https://www.benchmarkemail.com/help-FAQ/answer/how-does-one-add-a-txt-record-for-their-domain-having-dns-servers-hosted-with-godaddy

Have a good day (˵ ͡⚆ ͜ʖ ͡⚆˵)

**Comment by zstergios** [comment]
Thanks, I have managed to sovle this.
Thanks anyway it's usefull for new members
